#!/bin/sh

for i in $(seq 0 5 20)
do
    printf $i,
    FUNC_ARG=$i cargo bench | gsed -n 's/^test \(\S\+\) \+\.\.\. bench: \+\([0-9]\+\),\?\([0-9]\+\)\?,\?\([0-9]\+\)\? ns\/iter (+\/- \([0-9]\+\),\?\([0-9]\+\)\?,\?\([0-9]\+\)\?)$/\2\3\4,\5\6\7/p' | paste -s -d , -
done
