[package]
name = "client"
version = "0.0.0"
edition = "2018"

[dependencies]
serde_json = "1.0"

[dependencies.funs]
path = "../funs"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "client"
harness = false

