[package]
name = "client"
version = "0.0.0"
edition = "2018"

[dependencies.funs]
path = "../funs"

[dependencies.serde_json]
version = "1.0"

[dev-dependencies.bencher]
version = "0.1.5"

[dev-dependencies.lazy_static]
version = "1.4.0"

[[bench]]
name = "client"
harness = false

