[package]
name = "client"
version = "0.0.0"
edition = "2018"

[dependencies.funs]
path = "../funs"


[dependencies.serde_json]
version = "1.0"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "client"
harness = false

