[package]
name = "client"
version = "0.0.0"
edition = "2018"
serde = "1.0.126"

[dependencies.serde]
serde = "1.0.126"

[dev-dependencies.funs]
path = "../funs"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "client"
harness = false

