[package]
name = "server"
version = "0.0.0"
edition = "2018"

[dependencies.funs]
path = "../funs"

[dependencies.inger]
path = "../libinger"

[dependencies.log]
log = { version = "0.4.14", features = ["max_level_debug", "release_max_level_warn"]}

[dependencies.serde]
serde = "1.0.126"

[[bin]]
name = "main"
path = "src/main.rs"
[[bin]]
name = "q"
path = "src/q.rs"
