[package]
name = "server"
version = "0.0.0"
edition = "2018"
default-run = "main"
[dependencies.funs]
path = "../funs"

[dependencies.inger]
path = "../libinger"

[dependencies]
env_logger = "0.8.4"
log = { version = "0.4.14", features = ["max_level_debug", "release_max_level_warn"]}
serde = "1.0.126"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "q"
path = "src/q.rs"
