[package]
name = "server"
version = "0.0.0"
edition = "2018"

[dependencies.inger]
path = "../libinger"

[dependencies.funs]
path = "../funs"

[[bin]]
name = "main"
path = "src/main.rs"
[[bin]]
name = "q"
path = "src/q.rs"
